### ISSUE TITLE
Add passport js authentication to React site

### ISSUE THREAD

**Issue by joshghent** [esfiddle/site#1]
#### Type of issue
- [ ] Bug
- [x] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
Add passportjs authentication to the react site (branch `react-redesign`)
Allow users to login via github, twitter or Google

**Comment by collinmesser** [comment]
This issue is in reference to the React redesign. I'm going a new direction with Vue and this issue is now outdated.
