### ISSUE TITLE
Write some unit tests

### ISSUE THREAD

**Issue by collinmesser** [esfiddle/site#125]
### Type of issue

- [ ] Bug
- [x] Feature/Enhancement
- [ ] Question

### Description

We need to add unit tests to make sure that the project is well tested. It's best to get these started now while the project is young and we can add to them as we go. I'd say a goal for this initial issue/pr would be 80% coverage.

**Comment by ikrydev** [comment]
can i work on this ?
i will write unit test for components folder

please add hacktoberfest topics and hacktober label..

@collinmesser

**Comment by collinmesser** [comment]
@ikrydev Sure you can work on this! I added the hacktoberfest topic and label. Thanks!
