### ISSUE TITLE
Replace react-codemirror library

### ISSUE THREAD

**Issue by joshghent** [esfiddle/site#13]
#### Type of issue
- [x] Bug
- [ ] Idea/Suggestion
- [ ] Question

#### Description (include any screenshots or debugging information if applicable)
It appears that the code mirror library we are using is not maintained. We should move over to https://github.com/scniro/react-codemirror2

**Comment by konyan** [comment]
I want to fix this issues for my first time as contributor.

**Comment by joshghent** [comment]
I believe @collinmesser was talking about redoing this in Vue so best to speak with him first! Thank you for your interest in the project! 👍

**Comment by collinmesser** [comment]
Hey @konyan thanks for your interest. Sorry, I'm switching the new project over to Vue and this issue is no longer relevant. I'd recommend checking back in 1-2 weeks and there should be some new issues that would be good for first-time contributors.
