### ISSUE TITLE
Update webpack-dev-server

### ISSUE THREAD

**Issue by joshghent** [esfiddle/site#22]
### Remediation
Upgrade webpack-dev-server to version 3.1.11 or later. For example:

"dependencies": {
  "webpack-dev-server": ">=3.1.11"
}
or…
"devDependencies": {
  "webpack-dev-server": ">=3.1.11"
}
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by collinmesser** [comment]
Related to older react-backup branch. Not necessary now.
