### ISSUE TITLE
Up-for-grabs

### ISSUE THREAD

**Issue by ritwik12** [esfiddle/site#43]
#### Type of issue
- [x] Question

#### Description (include any screenshots or debugging information if applicable)
I can see that the site repo has changed but at up-for-grabs.net we still have the old repo link as reported to us in https://github.com/up-for-grabs/up-for-grabs.net/issues/1240. Please let us know what label you want to use now so that i will update the label link, or please send a PR for the same.

**Comment by shiftkey** [comment]
Also, it looks like the `up-for-grabs` label is no longer active. If someone would like to submit a PR to update this project it'd be greatly appreciated:

https://github.com/up-for-grabs/up-for-grabs.net/blob/5d4c4c45f22e644583eb8d984b4e12700a6a9706/_data/projects/esfiddle.yml#L10-L12

**Comment by shiftkey** [comment]
I think this has been fixed in https://github.com/up-for-grabs/up-for-grabs.net/pull/1255 - @joshghent are you able to close this out?

**Comment by joshghent** [comment]
@shiftkey With pleasure. Thanks a lot! Great to see you've got such an active community here!
